[package]
name = "grimoire"
version = "0.2.0"
edition = "2021"
authors = ["Nicholas Stienz <nickstienz@gmail.com>"]
license = "MIT"
description = "A CLI tool to write books"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
